# Generated by Django 6.0.1 on 2026-02-21 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notificacao',
        ),
    ]
