# Generated by Django 6.0.1 on 2026-03-19 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracaosistema',
            name='horario_fim_semana_fechamento',
        ),
        migrations.RemoveField(
            model_name='configuracaosistema',
            name='horario_semana_fechamento',
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='horario_fim_semana_fecho',
            field=models.TimeField(default='12:00'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='horario_semana_fecho',
            field=models.TimeField(default='16:00'),
        ),
        migrations.AlterField(
            model_name='configuracaosistema',
            name='email',
            field=models.EmailField(default='biblioteca@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='configuracaosistema',
            name='horario_fim_semana_abertura',
            field=models.TimeField(default='08:00'),
        ),
        migrations.AlterField(
            model_name='configuracaosistema',
            name='horario_semana_abertura',
            field=models.TimeField(default='08:00'),
        ),
        migrations.AlterField(
            model_name='configuracaosistema',
            name='telefone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
