# Generated by Django 6.0.1 on 2026-03-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='acao',
            field=models.CharField(choices=[('Sign up', 'Sign up'), ('Adicionou', 'Adicionou'), ('Criou', 'Criou'), ('Atualizou', 'Atualizou'), ('Removeu', 'Removeu'), ('Cancelou', 'Cancelou'), ('Aprovou', 'Aprovou')], max_length=20),
        ),
    ]
