# Generated by Django 6.0.1 on 2026-03-18 21:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0002_alter_auditlog_acao'),
        ('livros', '0002_livro_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('Atraso', 'Atraso na devolução'), ('Dano', 'Dano no material'), ('Perda', 'Perda do material'), ('Outro', 'Outro')], max_length=50)),
                ('descricao', models.TextField(blank=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('Pendente', 'Pendente'), ('Pago', 'Pago'), ('Dispensado', 'Dispensado')], default='Pendente', max_length=20)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_pagamento', models.DateTimeField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='multas_criadas', to=settings.AUTH_USER_MODEL)),
                ('emprestimo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='multas', to='livros.emprestimo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
