# Generated by Django 6.0.4 on 2026-05-12 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0002_configuracaosistema_limite_reservas_ativas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosistema',
            name='cobranca_ativa',
            field=models.BooleanField(default=True),
        ),
    ]
