# Generated by Django 6.0.1 on 2026-03-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0002_remove_configuracaosistema_horario_fim_semana_fechamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='acao',
            field=models.CharField(choices=[('Sign up', 'Sign up'), ('Adicionou', 'Adicionou'), ('Criou', 'Criou'), ('Atualizou', 'Atualizou'), ('Removeu', 'Removeu'), ('Finalizou', 'Finalizou'), ('Aprovou', 'Aprovou')], max_length=20),
        ),
    ]
