# Generated by Django 6.0.4 on 2026-05-28 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0003_configuracaosistema_cobranca_ativa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multa',
            name='valor',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
