# Generated by Django 6.0.1 on 2026-03-27 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0003_alter_auditlog_acao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracaosistema',
            options={'permissions': [('gerir_usuarios', 'Pode gerir usuários'), ('ver_relatorios', 'Pode ver relatórios')]},
        ),
    ]
