# Generated by Django 6.0.1 on 2026-02-26 19:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlunoOficial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_processo', models.CharField(help_text='Número de processo único do aluno', max_length=15, unique=True, validators=[django.core.validators.MinLengthValidator(5)])),
                ('nome_completo', models.CharField(help_text='Nome completo do aluno', max_length=100)),
                ('n_bilhete', models.CharField(help_text='Número de bilhete do aluno', max_length=30, validators=[django.core.validators.MinLengthValidator(5)])),
                ('curso', models.CharField(help_text='Curso do aluno', max_length=70)),
                ('classe', models.CharField(choices=[('10', '10ª Classe'), ('11', '11ª Classe'), ('12', '12ª Classe'), ('13', '13ª Classe')], help_text='Classe do aluno', max_length=2)),
                ('data_nascimento', models.DateField(help_text='Data de nascimento do aluno')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, help_text='Usuário do Django associado à conta do aluno', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aluno Oficial',
                'verbose_name_plural': 'Alunos Oficiais',
                'ordering': ['nome_completo'],
            },
        ),
    ]
