# Generated by Django 6.0.1 on 2026-02-27 11:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0004_alunooficial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunooficial',
            name='n_bilhete',
            field=models.CharField(help_text='Número de bilhete do aluno', max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
