# Generated by Django 6.0.4 on 2026-05-28 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0004_alter_multa_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multa',
            name='valor',
            field=models.IntegerField(),
        ),
    ]
