# Generated by Django 6.0.1 on 2026-03-29 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0004_alter_configuracaosistema_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuditLog',
        ),
    ]
