# Generated by Django 6.0.1 on 2026-02-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0005_alter_alunooficial_n_bilhete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='acao',
            field=models.CharField(choices=[('signin', 'Se cadastrou'), ('create', 'Criou'), ('update', 'Atualizou'), ('delete', 'Removeu'), ('approve', 'Aprovou')], max_length=20),
        ),
    ]
