# Generated by Django 6.0.4 on 2026-05-28 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0006_alter_multa_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaosistema',
            name='multa_por_dano',
            field=models.DecimalField(decimal_places=0, default=1500, max_digits=10),
        ),
        migrations.AlterField(
            model_name='configuracaosistema',
            name='multa_por_dia',
            field=models.DecimalField(decimal_places=0, default=500, max_digits=10),
        ),
        migrations.AlterField(
            model_name='configuracaosistema',
            name='multa_por_perda',
            field=models.DecimalField(decimal_places=0, default=5000, max_digits=10),
        ),
    ]
