# Generated by Django 6.0.4 on 2026-05-28 02:32

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0007_alter_configuracaosistema_multa_por_dano_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaosistema',
            name='multa_por_dano',
            field=models.DecimalField(decimal_places=0, default=5, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='configuracaosistema',
            name='multa_por_dia',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='configuracaosistema',
            name='multa_por_perda',
            field=models.DecimalField(decimal_places=0, default=5, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
