# Generated by Django 6.0.4 on 2026-05-28 02:42

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0008_alter_configuracaosistema_multa_por_dano_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracaosistema',
            options={'permissions': [('gerir_usuarios', 'Pode gerir usuários'), ('ver_relatorios', 'Pode ver relatórios')], 'verbose_name': 'Configuração do Sistema', 'verbose_name_plural': 'Configuração do Sistema'},
        ),
        migrations.AlterField(
            model_name='configuracaosistema',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='configuracaosistema',
            name='horario_fim_semana_abertura',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AlterField(
            model_name='configuracaosistema',
            name='horario_fim_semana_fecho',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
        migrations.AlterField(
            model_name='configuracaosistema',
            name='horario_semana_abertura',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AlterField(
            model_name='configuracaosistema',
            name='horario_semana_fecho',
            field=models.TimeField(default=datetime.time(16, 0)),
        ),
        migrations.AlterField(
            model_name='configuracaosistema',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Número de telefone inválido.', regex='^\\+?[0-9]{7,15}$')]),
        ),
    ]
