# Generated by Django 6.0.4 on 2026-05-28 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0009_alter_configuracaosistema_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuracaosistema',
            old_name='multa_por_dano',
            new_name='dias_tolerancia',
        ),
        migrations.RenameField(
            model_name='configuracaosistema',
            old_name='multa_por_perda',
            new_name='multa_por_perda_ou_dano',
        ),
    ]
