# Generated by Django 6.0.1 on 2026-01-29 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('nome', models.CharField(max_length=120)),
                ('n_processo', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('curso', models.CharField(blank=True, max_length=100)),
                ('classe', models.CharField(blank=True, max_length=20)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('n_reservas', models.IntegerField(default=0)),
                ('n_emprestimos', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('nacionalidade', models.CharField(max_length=60)),
                ('total_obras', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, unique=True)),
                ('descricao', models.CharField(default='', max_length=250)),
                ('n_livros', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('publicado_em', models.DateField()),
                ('estado', models.CharField(choices=[('disponivel', 'Disponível'), ('reservado', 'Reservado'), ('emprestado', 'Emprestado'), ('pendente', 'Pendente')], default='disponivel', max_length=20)),
                ('informacao', models.CharField(default='Reservar Livro', max_length=30)),
                ('sumario', models.TextField()),
                ('editora', models.CharField(max_length=45)),
                ('n_paginas', models.PositiveIntegerField(default=1)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livros', to='livros.autor')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livros', to='livros.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('disponivel', 'Disponível'), ('reservado', 'Reservado'), ('emprestado', 'Emprestado'), ('pendente', 'Pendente')], default='pendente', max_length=20)),
                ('data_reserva', models.DateField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='livros.aluno')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='livros.autor')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='livros.livro')),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('disponivel', 'Disponível'), ('reservado', 'Reservado'), ('emprestado', 'Emprestado'), ('pendente', 'Pendente')], default='emprestado', max_length=20)),
                ('data_emprestimo', models.DateField(auto_now_add=True)),
                ('data_devolucao', models.DateField(blank=True, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos', to='livros.aluno')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos', to='livros.autor')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos', to='livros.livro')),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emprestimo', to='livros.reserva')),
            ],
        ),
    ]
