# Generated by Django 6.0.1 on 2026-02-27 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracao', '0005_alter_alunooficial_n_bilhete'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('nacionalidade', models.CharField(max_length=60)),
                ('total_obras', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, unique=True)),
                ('descricao', models.CharField(default='', max_length=250)),
                ('n_livros', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('estado', models.CharField(choices=[('Ativo', 'Ativo'), ('Suspenso', 'Suspenso')], default='Ativo', max_length=20)),
                ('n_reservas', models.IntegerField(default=0)),
                ('n_emprestimos', models.IntegerField(default=0)),
                ('aluno_oficial', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to='administracao.alunooficial')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('estado', models.CharField(choices=[('Disponível', 'Disponível'), ('Indisponível', 'Indisponível')], default='Disponível', max_length=20)),
                ('publicado_em', models.DateField()),
                ('descricao', models.TextField(blank=True, null=True)),
                ('sumario', models.TextField()),
                ('editora', models.CharField(max_length=45)),
                ('n_paginas', models.PositiveIntegerField(default=1)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('capa', models.URLField(max_length=500)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livros', to='livros.autor')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livros', to='livros.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(default='Geral')),
                ('lida', models.BooleanField(default=False)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendente', 'Pendente'), ('reservado', 'Reservado'), ('aprovada', 'Aprovada'), ('finalizada', 'Finalizada')], default='pendente', max_length=20)),
                ('data_reserva', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='livros.aluno')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='livros.livro')),
            ],
            options={
                'ordering': ['-data_reserva'],
            },
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acoes', models.CharField(choices=[('ativo', 'Ativo'), ('atrasado', 'Atrasado'), ('devolvido', 'Devolvido')], default='ativo', max_length=20)),
                ('data_emprestimo', models.DateField(auto_now_add=True)),
                ('data_devolucao', models.DateField()),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emprestimo', to='livros.reserva')),
            ],
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.UniqueConstraint(condition=models.Q(('estado__in', ['pendente', 'reservado'])), fields=('aluno', 'livro'), name='unique_active_reserva'),
        ),
    ]
