# Generated by Django 6.0.1 on 2026-04-19 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='fila',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livro',
            name='prateleira',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
