# Generated by Django 6.0.4 on 2026-04-28 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_livro_fila_livro_prateleira'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participacao',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participacoes', to='livros.evento'),
        ),
        migrations.AlterField(
            model_name='participacao',
            name='exposicao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participacoes', to='livros.exposicao'),
        ),
    ]
