# Generated by Django 6.0.1 on 2026-01-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_livro_capa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='capa',
            field=models.URLField(default='https://res.cloudinary.com/degsmhalt/image/upload/v1765812599/livro02_hawwht.webp', max_length=500),
            preserve_default=False,
        ),
    ]
