# Generated by Django 6.0.1 on 2026-03-24 10:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_livro_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='data_aprovacao',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='acoes',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('atrasado', 'Atrasado'), ('devolvido', 'Devolvido')], db_index=True, default='ativo', max_length=20),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_devolucao',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='livro',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('reservado', 'Reservado'), ('aprovada', 'Aprovada'), ('finalizada', 'Finalizada'), ('expirada', 'Expirada')], db_index=True, default='pendente', max_length=20),
        ),
        migrations.AddIndex(
            model_name='emprestimo',
            index=models.Index(fields=['acoes', 'data_devolucao'], name='livros_empr_acoes_fdc12f_idx'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['estado', 'data_aprovacao'], name='livros_rese_estado_11554e_idx'),
        ),
    ]
