# Generated by Django 6.0.4 on 2026-04-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0003_alter_participacao_evento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='data_fim',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_inicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='exposicao',
            name='data_fim',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='exposicao',
            name='data_inicio',
            field=models.DateField(),
        ),
    ]
