# Generated by Django 6.0.1 on 2026-03-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0003_reserva_data_aprovacao_alter_emprestimo_acoes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('reservado', 'Reservado'), ('em_uso', 'Em Uso'), ('finalizada', 'Finalizada'), ('expirada', 'Expirada')], db_index=True, default='pendente', max_length=20),
        ),
    ]
