# Generated by Django 6.0.1 on 2026-01-29 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0003_alter_livro_capa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='informacao',
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='acoes',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('atrasado', 'Atrasado'), ('devolvido', 'Devolvido')], default='ativo', max_length=20),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('reservado', 'Reservado'), ('pendente', 'Pendente')], default='pendente', max_length=20),
        ),
    ]
