# Generated by Django 6.0.1 on 2026-03-24 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0004_alter_reserva_estado'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reserva',
            name='unique_active_reserva',
        ),
        migrations.RemoveIndex(
            model_name='reserva',
            name='livros_rese_estado_11554e_idx',
        ),
    ]
