# Generated by Django 6.0.1 on 2026-01-30 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0004_remove_emprestimo_estado_remove_livro_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='descricao',
            field=models.TextField(blank=True, help_text='Descrição detalhada do livro', null=True),
        ),
    ]
