# Generated by Django 6.0.4 on 2026-05-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0004_alter_evento_data_fim_alter_evento_data_inicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='stock_descontado',
            field=models.BooleanField(default=False),
        ),
    ]
