# Generated by Django 6.0.1 on 2026-01-30 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0005_livro_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='capa',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
