# Generated by Django 6.0.1 on 2026-01-30 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0006_reserva_capa'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='capa',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_devolucao',
            field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('reservado', 'Reservado'), ('pendente', 'Pendente'), ('emprestado', 'Emprestado')], default='pendente', max_length=20),
        ),
    ]
