# Generated by Django 6.0.1 on 2026-01-30 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0007_emprestimo_capa_alter_emprestimo_data_devolucao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='capa',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='capa',
        ),
    ]
