# Generated by Django 6.0.1 on 2026-02-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0008_remove_emprestimo_capa_remove_reserva_capa'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='estado',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('indisponivel', 'Indisponível')], default='disponivel', max_length=20),
        ),
    ]
