# Generated by Django 6.0.1 on 2026-02-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0009_livro_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='estado',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('suspenso', 'Suspenso')], default='ativo', max_length=20),
        ),
    ]
