# Generated by Django 6.0.1 on 2026-02-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0010_aluno_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='estado',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Suspenso', 'Suspenso')], default='Ativo', max_length=20),
        ),
    ]
