# Generated by Django 6.0.1 on 2026-02-06 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0011_alter_aluno_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='autor',
        ),
    ]
