# Generated by Django 6.0.1 on 2026-02-07 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0012_remove_emprestimo_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='autor',
        ),
    ]
