# Generated by Django 6.0.1 on 2026-02-07 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0013_remove_reserva_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='autor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='livros.autor'),
            preserve_default=False,
        ),
    ]
