# Generated by Django 6.0.1 on 2026-02-09 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0017_remove_reserva_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='emprestimo',
            name='livro',
        ),
    ]
