# Generated by Django 6.0.1 on 2026-02-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0018_remove_emprestimo_aluno_remove_emprestimo_livro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('reservado', 'Reservado'), ('pendente', 'Pendente'), ('emprestado', 'Emprestado'), ('finalizada', 'Finalizada')], default='pendente', max_length=20),
        ),
    ]
