# Generated by Django 6.0.1 on 2026-02-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0019_alter_reserva_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('reservado', 'Reservado'), ('aprovada', 'Aprovada'), ('finalizada', 'Finalizada')], default='pendente', max_length=20),
        ),
    ]
