# Generated by Django 6.0.1 on 2026-02-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0020_alter_reserva_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='data_reserva',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
