# Generated by Django 6.0.1 on 2026-02-16 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0021_alter_reserva_data_reserva'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='email',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='password',
        ),
        migrations.AddField(
            model_name='aluno',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='livro',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
