# Generated by Django 6.0.1 on 2026-02-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0022_remove_aluno_email_remove_aluno_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='estado',
            field=models.CharField(choices=[('Disponível', 'Disponível'), ('Indisponível', 'Indisponível')], default='disponivel', max_length=20),
        ),
    ]
