# Generated by Django 6.0.1 on 2026-02-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0024_alter_livro_estado_notificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
