# Generated by Django 6.0.1 on 2026-03-03 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('estado', models.CharField(choices=[('Ativo', 'Ativo'), ('Suspenso', 'Suspenso')], default='Ativo', max_length=20)),
                ('n_reservas', models.IntegerField(default=0)),
                ('n_emprestimos', models.IntegerField(default=0)),
                ('funcionario_oficial', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to='accounts.funcionariooficial')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
