# Generated by Django 6.0.4 on 2026-05-26 22:17

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_perfil_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='foto',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='foto_perfil'),
        ),
    ]
